module ConnpassApiV2
  class Client
    @api_key: String

    API_ENDPOINT: string

    def initialize: (String api_key) -> void

    def inspect: () -> String

    def self.joined_param: (untyped param) -> String?

    def self.to_ymd: ((String | Date)? param) -> String?

    def self.to_ym: ((String | Date)? param) -> String?

    def self.to_order_num: ((Integer | Symbol)? order) -> Integer?

    private

    def connection: () -> Faraday::Connection
  end
end
