module ConnpassApiV2
  class Client
    module EventMethods
      def get_events: (
        ?event_id: (Integer | Array[Integer])?,
        ?keyword: (String | Array[String])?,
        ?keyword_or: (String | Array[String])?,
        ?ym: (String | Array[String] | Date | Array[Date])?,
        ?ymd: (String | Array[String] | Date | Array[Date])?,
        ?nickname: (String | Array[String])?,
        ?owner_nickname: (String | Array[String])?,
        ?group_id: (Integer | Array[Integer])?,
        ?subdomain: (String | Array[String])?,
        ?prefecture: (String | Array[String])?,
        ?order: (Integer | Symbol)?,
        ?start: Integer?,
        ?count: Integer?,
      ) -> Response

      def get_event_presentations: (
        Integer event_id,
        ?start: Integer?,
        ?count: Integer?,
      ) -> Response
    end
  end
end
