module ConnpassApiV2
  class Client
    module UserMethods
      def get_users: (
        ?nickname: (String | Array[String])?,
        ?start: Integer?,
        ?count: Integer?,
      ) -> Response

      def get_user_groups: (
        String  nickname,
        ?start: Integer?,
        ?count: Integer?,
      ) -> Response

      def get_user_attended_events: (
        String  nickname,
        ?start: Integer?,
        ?count: Integer?,
      ) -> Response
    end
  end
end
